# Generated by Django 4.1.4 on 2022-12-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drugInterectionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1_id', models.CharField(max_length=20)),
                ('drug1_name', models.CharField(max_length=255)),
                ('drug2_id', models.CharField(max_length=20)),
                ('drug2_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
            ],
        ),
    ]
